# Generated by Django 5.2.7 on 2025-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField()),
                ('erro', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação de Email',
                'verbose_name_plural': 'Notificações de Email',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('numero_protocolo_tarefa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('indicador_subtarefas_pendentes', models.IntegerField()),
                ('codigo_unidade_tarefa', models.IntegerField()),
                ('nome_servico', models.CharField(max_length=255)),
                ('status_tarefa', models.CharField(max_length=100)),
                ('descricao_cumprimento_exigencia_tarefa', models.TextField(blank=True, null=True)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável')),
                ('nome_profissional_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_gex_responsavel', models.CharField(blank=True, max_length=10, null=True)),
                ('nome_gex_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('data_distribuicao_tarefa', models.DateField(blank=True, null=True)),
                ('data_ultima_atualizacao', models.DateField(blank=True, null=True)),
                ('data_fim_ultima_exigencia', models.DateField(blank=True, null=True)),
                ('data_processamento_tarefa', models.DateTimeField(blank=True, null=True)),
                ('tempo_ultima_exigencia_em_dias', models.IntegerField(blank=True, null=True)),
                ('tempo_em_pendencia_em_dias', models.IntegerField(default=0)),
                ('tempo_em_exigencia_em_dias', models.IntegerField(default=0)),
                ('tempo_ate_ultima_distribuicao_tarefa_em_dias', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-data_distribuicao_tarefa'],
            },
        ),
    ]
