# Generated by Django 5.2.7 on 2025-10-22 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaoemail',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacaoemail',
            name='remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='siape_responsavel',
            field=models.ForeignKey(blank=True, db_column='siape_responsavel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_sob_responsabilidade', to=settings.AUTH_USER_MODEL, to_field='siape'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['status_tarefa'], name='tarefas_tar_status__b5e4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['siape_responsavel'], name='tarefas_tar_siape_r_f947dc_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['data_distribuicao_tarefa'], name='tarefas_tar_data_di_ed6bc8_idx'),
        ),
    ]
