# Generated by Django 5.2.7 on 2025-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='numero_protocolo_tarefa',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número do Protocolo'),
        ),
    ]
