# Generated by Django 5.2.7 on 2025-10-22 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_numero_protocolo_tarefa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_inicio_ultima_exigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início da Última Exigência'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Prazo'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='indicador_tarefa_reaberta',
            field=models.IntegerField(default=0, verbose_name='Indicador de Tarefa Reaberta'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['data_prazo'], name='tarefas_tar_data_pr_f7550c_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['indicador_tarefa_reaberta'], name='tarefas_tar_indicad_5c57e4_idx'),
        ),
    ]
