# Generated by Django 5.2.7 on 2025-10-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefa_data_inicio_ultima_exigencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_analise_exigencia_cumprida', models.IntegerField(default=7, help_text='Prazo que o servidor tem para analisar uma exigência após ela ser cumprida. Padrão: 7 dias. REGRA 1.', verbose_name='Prazo para Análise de Exigência Cumprida (dias)')),
                ('prazo_tolerancia_exigencia', models.IntegerField(default=5, help_text='Dias adicionais após a data do prazo para o segurado cumprir a exigência. Padrão: 5 dias. REGRA 2.', verbose_name='Tolerância Adicional para Cumprimento de Exigência (dias)')),
                ('prazo_servidor_apos_vencimento', models.IntegerField(default=7, help_text='Prazo que o servidor tem para concluir a tarefa após vencimento da exigência. Padrão: 7 dias. REGRA 2.', verbose_name='Prazo do Servidor Após Vencimento da Exigência (dias)')),
                ('prazo_primeira_acao', models.IntegerField(default=10, help_text='Prazo que o servidor tem para realizar a primeira ação em uma tarefa. Padrão: 10 dias. REGRAS 3 e 4.', verbose_name='Prazo para Primeira Ação (dias)')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se esta é a configuração ativa do sistema. Deve haver apenas UMA configuração ativa.', verbose_name='Configuração Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario_atualizacao', models.CharField(blank=True, help_text='Nome do usuário que fez a última atualização', max_length=255, null=True, verbose_name='Usuário que Atualizou')),
                ('observacoes', models.TextField(blank=True, help_text='Motivo da alteração dos parâmetros ou observações gerais', null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Configuração de Prazos',
                'verbose_name_plural': 'Configurações de Prazos',
                'ordering': ['-ativo', '-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracaoPrazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('usuario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário')),
                ('campo_alterado', models.CharField(max_length=100, verbose_name='Campo Alterado')),
                ('valor_anterior', models.IntegerField(verbose_name='Valor Anterior')),
                ('valor_novo', models.IntegerField(verbose_name='Valor Novo')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo da Alteração')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='tarefas.parametrosanalise', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração de Prazo',
                'verbose_name_plural': 'Histórico de Alterações de Prazos',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
