# Generated by Django 5.2.7 on 2025-10-24 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_parametrosanalise_historicoalteracaoprazos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='alerta_criticidade_calculado',
            field=models.TextField(blank=True, default='', verbose_name='Alerta de Criticidade (Calculado)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='cor_criticidade_calculado',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Cor (Calculado)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_calculo_criticidade',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Último Cálculo'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao_criticidade_calculado',
            field=models.TextField(blank=True, default='', verbose_name='Descrição Detalhada (Calculado)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='dias_pendente_criticidade_calculado',
            field=models.IntegerField(default=0, verbose_name='Dias Pendente (Calculado)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='nivel_criticidade_calculado',
            field=models.CharField(choices=[('CRÍTICA', 'Crítica'), ('ALTA', 'Alta'), ('MÉDIA', 'Média'), ('BAIXA', 'Baixa'), ('NENHUMA', 'Nenhuma')], db_index=True, default='NENHUMA', max_length=10, verbose_name='Nível de Criticidade (Calculado)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='pontuacao_criticidade',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Pontuação para Ordenação'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prazo_limite_criticidade_calculado',
            field=models.IntegerField(default=0, verbose_name='Prazo Limite (Calculado)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='regra_aplicada_calculado',
            field=models.CharField(db_index=True, default='NENHUMA', max_length=20, verbose_name='Regra Aplicada (Calculado)'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['nivel_criticidade_calculado'], name='tarefas_tar_nivel_c_7f4604_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['pontuacao_criticidade'], name='tarefas_tar_pontuac_aec48d_idx'),
        ),
    ]
