# Generated by Django 5.2.7 on 2025-10-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_simplificar_criticidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(help_text='Explicação detalhada sobre quando usar este tipo', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Se desmarcado, não aparecerá como opção', verbose_name='Ativo')),
                ('ordem_exibicao', models.IntegerField(default=0, help_text='Ordem em que aparece na lista (menor = primeiro)', verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Justificativa',
                'verbose_name_plural': 'Tipos de Justificativas',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='servico_excluido_criticidade',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Serviço Excluído da Criticidade'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tem_justificativa_ativa',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Possui Justificativa Aprovada'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tem_solicitacao_ajuda',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Possui Solicitação de Ajuda'),
        ),
        migrations.CreateModel(
            name='ServicosCriticidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(db_index=True, help_text='Nome exato do serviço conforme aparece nas tarefas', max_length=255, unique=True, verbose_name='Nome do Serviço')),
                ('excluido_criticidade', models.BooleanField(default=True, help_text='Se marcado, tarefas deste serviço NÃO serão consideradas críticas', verbose_name='Excluído da Criticidade')),
                ('motivo_exclusao', models.TextField(blank=True, help_text='Explique por que este serviço está sendo excluído', verbose_name='Motivo da Exclusão')),
                ('data_configuracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Configuração')),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Alteração')),
                ('configurado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_configurados', to=settings.AUTH_USER_MODEL, verbose_name='Configurado Por')),
            ],
            options={
                'verbose_name': 'Configuração de Serviço',
                'verbose_name_plural': 'Configurações de Serviços',
                'ordering': ['nome_servico'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Explique qual dificuldade está enfrentando', verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Atendimento'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início do Atendimento')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes_atendimento', models.TextField(blank=True, help_text='Registre as ações tomadas e orientações dadas', verbose_name='Observações do Atendimento')),
                ('protocolo_original', models.CharField(db_index=True, max_length=20, verbose_name='Protocolo Original')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_ajuda_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendido Por')),
                ('servidor_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_ajuda_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Servidor Solicitante')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_ajuda', to='tarefas.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Solicitação de Ajuda',
                'verbose_name_plural': 'Solicitações de Ajuda',
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['status', 'data_solicitacao'], name='tarefas_sol_status_02860f_idx'), models.Index(fields=['servidor_solicitante', 'status'], name='tarefas_sol_servido_972931_idx')],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Explique detalhadamente a situação', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Análise'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Status')),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise')),
                ('parecer', models.TextField(blank=True, help_text='Comentário da Equipe Volante sobre a decisão', verbose_name='Parecer')),
                ('protocolo_original', models.CharField(db_index=True, help_text='Número do protocolo no momento da submissão', max_length=20, verbose_name='Protocolo Original')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analisado Por')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_submetidas', to=settings.AUTH_USER_MODEL, verbose_name='Servidor')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='tarefas.tarefa', verbose_name='Tarefa')),
                ('tipo_justificativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificativas', to='tarefas.tipojustificativa', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ['-data_submissao'],
                'indexes': [models.Index(fields=['status', 'data_submissao'], name='tarefas_jus_status_21ace5_idx'), models.Index(fields=['servidor', 'status'], name='tarefas_jus_servido_5a0bb2_idx')],
            },
        ),
    ]
