# Generated by Django 5.2.7 on 2025-10-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_tipojustificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='regra_aplicada_calculado',
            field=models.CharField(db_index=True, default='NENHUMA', max_length=50, verbose_name='Regra Aplicada (Calculado)'),
        ),
    ]
