# Generated by Django 5.2.7 on 2025-11-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_alter_tarefa_regra_aplicada_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nivel_criticidade_calculado',
            field=models.CharField(choices=[('CRÍTICA', 'Crítica'), ('REGULAR', 'Regular'), ('JUSTIFICADA', 'Justificada'), ('EXCLUÍDA', 'Excluída')], db_index=True, default='REGULAR', max_length=15, verbose_name='Nível de Criticidade (Calculado)'),
        ),
    ]
