# Generated by Django 5.2.7 on 2025-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_ajustar_tamanho_nivel_criticidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tipo_fila',
            field=models.CharField(db_index=True, default='OUTROS', help_text='Classificação automática da tarefa em filas de trabalho', max_length=50, verbose_name='Tipo de Fila'),
        ),
    ]
