# Generated by Django 5.2.7 on 2025-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0011_adicionar_tipo_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True, help_text='False = tarefa arquivada (não aparece mais nos CSVs importados)', verbose_name='Tarefa Ativa'),
        ),
    ]
