# Generated by Django 5.2.7 on 2025-11-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0012_adicionar_campo_ativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(db_index=True, help_text='Nome exato do serviço conforme aparece nas tarefas', max_length=255, verbose_name='Nome do Serviço')),
                ('codigo_unidade', models.IntegerField(blank=True, db_index=True, help_text='Código da unidade do INSS (ex: 23150521, 23150003). Deixe em branco para aplicar a todas as unidades.', null=True, verbose_name='Código da Unidade')),
                ('tipo_fila', models.CharField(choices=[('PGB', 'PGB - Posto de Gerenciamento de Benefícios'), ('CEABRD-23150521', 'CEABRD - Benefícios Regulares e Diretos'), ('CEAB-BI-23150521', 'CEAB-BI - Benefícios por Incapacidade'), ('CEAB-RECURSO-23150521', 'CEAB-RECURSO - Recursos'), ('CEAB-DEFESO-23150521', 'CEAB-DEFESO - Seguro Defeso'), ('CEAB-COMPREV-23150521', 'CEAB-COMPREV - Compensação Previdenciária'), ('CEAB-MOB-23150521', 'CEAB-MOB - Apuração de Irregularidades'), ('OUTROS', 'OUTROS - Outras Tarefas')], db_index=True, help_text='Fila para a qual este serviço será direcionado', max_length=50, verbose_name='Fila de Destino')),
                ('prioridade', models.IntegerField(default=100, help_text='Regras com prioridade menor são aplicadas primeiro (1 = maior prioridade)', verbose_name='Prioridade')),
                ('ativa', models.BooleanField(db_index=True, default=True, help_text='Se desmarcado, esta regra será ignorada na classificação', verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações sobre esta configuração', verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_fila_alteradas', to=settings.AUTH_USER_MODEL, verbose_name='Alterado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_fila_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Configuração de Fila',
                'verbose_name_plural': 'Configurações de Filas',
                'ordering': ['prioridade', 'tipo_fila', 'nome_servico'],
                'indexes': [models.Index(fields=['nome_servico', 'codigo_unidade', 'ativa'], name='tarefas_con_nome_se_85e931_idx'), models.Index(fields=['tipo_fila', 'ativa'], name='tarefas_con_tipo_fi_078346_idx'), models.Index(fields=['prioridade', 'ativa'], name='tarefas_con_priorid_8eb14c_idx')],
            },
        ),
    ]
