# Generated by Django 5.2.7 on 2025-11-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0013_configuracaofila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaofila',
            options={'ordering': ['prioridade', 'tipo_fila', 'nome_servico'], 'verbose_name': '⚙️ Configuração de Fila', 'verbose_name_plural': '⚙️ Configurações de Filas (Classificação Automática)'},
        ),
        migrations.AlterField(
            model_name='configuracaofila',
            name='tipo_fila',
            field=models.CharField(db_index=True, help_text='Código da fila para a qual este serviço será direcionado (ex: PGB, CEABRD-23150521)', max_length=50, verbose_name='Fila de Destino'),
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único identificador (ex: PGB, CEABRD-23150521, CEAB-BI-23150521)', max_length=50, unique=True, verbose_name='Código da Fila')),
                ('nome', models.CharField(help_text='Nome curto para exibição (ex: PGB, CEABRD, CEAB-BI)', max_length=100, verbose_name='Nome Curto')),
                ('nome_completo', models.CharField(help_text='Nome completo descritivo da fila', max_length=255, verbose_name='Nome Completo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada sobre o tipo de tarefas desta fila', verbose_name='Descrição')),
                ('cor', models.CharField(default='#6c757d', help_text='Cor em formato hexadecimal (ex: #007bff)', max_length=7, verbose_name='Cor (Hexadecimal)')),
                ('icone', models.CharField(default='fas fa-folder', help_text='Classe do ícone FontAwesome (ex: fas fa-building)', max_length=50, verbose_name='Ícone (FontAwesome)')),
                ('ordem', models.IntegerField(default=100, help_text='Define a ordem de exibição nas listagens (menor = primeiro)', verbose_name='Ordem de Exibição')),
                ('ativa', models.BooleanField(db_index=True, default=True, help_text='Se desmarcado, esta fila não aparecerá mais nas opções', verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas_alteradas', to=settings.AUTH_USER_MODEL, verbose_name='Alterado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': '📋 Fila de Trabalho',
                'verbose_name_plural': '📋 Filas de Trabalho',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['codigo', 'ativa'], name='tarefas_fil_codigo_f4c969_idx'), models.Index(fields=['ordem', 'ativa'], name='tarefas_fil_ordem_f9902f_idx')],
            },
        ),
    ]
