# Generated by Django 5.2.7 on 2025-11-07 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0014_alter_configuracaofila_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fila', models.CharField(max_length=20, verbose_name='Código da Fila')),
                ('tipo_acao', models.CharField(choices=[('BLOQUEIO', 'Bloquear Caixa'), ('DESBLOQUEIO', 'Desbloquear Caixa')], max_length=20, verbose_name='Tipo de Ação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Processamento')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conclusão')),
                ('resposta_robo', models.TextField(blank=True, verbose_name='Resposta do Robô')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('servidor', models.ForeignKey(db_column='siape_servidor', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to=settings.AUTH_USER_MODEL, verbose_name='Servidor (SIAPE)')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado Por')),
            ],
            options={
                'verbose_name': 'Bloqueio de Servidor',
                'verbose_name_plural': '🔒 Bloqueios de Servidores',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoBloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fila', models.CharField(max_length=20, verbose_name='Código da Fila')),
                ('tipo_acao', models.CharField(max_length=20, verbose_name='Tipo de Ação')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes da Ação')),
                ('resposta_robo', models.TextField(blank=True, verbose_name='Resposta do Robô')),
                ('bloqueio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='tarefas.bloqueioservidor', verbose_name='Bloqueio')),
                ('executado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_executados', to=settings.AUTH_USER_MODEL, verbose_name='Executado Por')),
                ('servidor', models.ForeignKey(db_column='siape_servidor', on_delete=django.db.models.deletion.CASCADE, related_name='historico_bloqueios', to=settings.AUTH_USER_MODEL, verbose_name='Servidor (SIAPE)')),
            ],
            options={
                'verbose_name': 'Histórico de Bloqueio',
                'verbose_name_plural': '📜 Histórico de Bloqueios',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(max_length=254, verbose_name='Email Destinatário')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('corpo_email', models.TextField(verbose_name='Corpo do Email')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data do Envio')),
                ('resposta_api', models.TextField(blank=True, verbose_name='Resposta da API Microsoft Graph')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
                ('servidor', models.ForeignKey(db_column='siape_servidor', on_delete=django.db.models.deletion.CASCADE, related_name='historico_emails', to=settings.AUTH_USER_MODEL, verbose_name='Servidor Destinatário')),
            ],
            options={
                'verbose_name': 'Histórico de Email',
                'verbose_name_plural': '📧 Histórico de Emails',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacao', models.CharField(choices=[('PRIMEIRA_NOTIFICACAO', 'PGB - Primeira Notificação'), ('SEGUNDA_NOTIFICACAO', 'PGB - Segunda Notificação')], max_length=30, verbose_name='Tipo de Notificação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Processamento')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conclusão')),
                ('numero_protocolo_criado', models.CharField(blank=True, max_length=20, verbose_name='Número do Protocolo Criado')),
                ('resposta_robo', models.TextField(blank=True, verbose_name='Resposta do Robô')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('servidor', models.ForeignKey(db_column='siape_servidor', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_pgb', to=settings.AUTH_USER_MODEL, verbose_name='Servidor (SIAPE)')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado Por')),
            ],
            options={
                'verbose_name': 'Solicitação de Notificação PGB',
                'verbose_name_plural': '📋 Solicitações de Notificações PGB',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacao', models.CharField(max_length=30, verbose_name='Tipo de Notificação')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes da Ação')),
                ('numero_protocolo', models.CharField(blank=True, max_length=20, verbose_name='Número do Protocolo')),
                ('resposta_robo', models.TextField(blank=True, verbose_name='Resposta do Robô')),
                ('executado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_executadas', to=settings.AUTH_USER_MODEL, verbose_name='Executado Por')),
                ('servidor', models.ForeignKey(db_column='siape_servidor', on_delete=django.db.models.deletion.CASCADE, related_name='historico_notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Servidor (SIAPE)')),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='tarefas.solicitacaonotificacao', verbose_name='Notificação')),
            ],
            options={
                'verbose_name': 'Histórico de Notificação',
                'verbose_name_plural': '📜 Histórico de Notificações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto do Email')),
                ('corpo_html', models.TextField(verbose_name='Corpo do Email (HTML)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': '✉️ Templates de Email',
                'ordering': ['nome'],
            },
        ),
    ]
