# Generated by Django 5.2.7 on 2025-11-12 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0015_bloqueioservidor_historicobloqueio_historicoemail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['ativa', 'siape_responsavel', 'tipo_fila'], name='tarefas_tar_ativa_87a494_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['ativa', 'tipo_fila', 'nivel_criticidade_calculado'], name='tarefas_tar_ativa_94d8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['data_processamento_tarefa'], name='tarefas_tar_data_pr_06112c_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['ativa', 'siape_responsavel'], name='tarefas_tar_ativa_033535_idx'),
        ),
    ]
