# Generated by Django 5.2.7 on 2025-11-13 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0016_adicionar_indices_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAcaoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fila', models.CharField(max_length=50, verbose_name='Código da Fila')),
                ('tipo_acao', models.CharField(choices=[('REMOVER_RESPONSAVEL', 'Remover Responsável em Lote (Tipo 14)'), ('TRANSFERIR_TAREFA', 'Transferir Tarefa em Lote (Tipo 12)')], max_length=30, verbose_name='Tipo de Ação')),
                ('criterio_selecao', models.CharField(help_text='TODAS, SERVICO, QUANTIDADE ou MANUAL', max_length=20, verbose_name='Critério de Seleção')),
                ('servico_selecionado', models.CharField(blank=True, max_length=255, verbose_name='Serviço Selecionado')),
                ('quantidade_tarefas', models.IntegerField(verbose_name='Quantidade de Tarefas no Arquivo')),
                ('uo_destino', models.CharField(blank=True, max_length=20, verbose_name='UO de Destino')),
                ('despacho', models.TextField(blank=True, verbose_name='Despacho')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo Gerado')),
                ('protocolos_incluidos', models.TextField(help_text='Lista de protocolos incluídos no arquivo (separados por vírgula)', verbose_name='Protocolos Incluídos')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_lote_geradas', to=settings.AUTH_USER_MODEL, verbose_name='Gerado Por')),
                ('servidor', models.ForeignKey(db_column='siape_servidor', on_delete=django.db.models.deletion.CASCADE, related_name='historico_acoes_lote', to=settings.AUTH_USER_MODEL, verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Histórico de Ação em Lote',
                'verbose_name_plural': '📄 Histórico de Ações em Lote',
                'ordering': ['-data_geracao'],
                'indexes': [models.Index(fields=['servidor', 'data_geracao'], name='tarefas_his_siape_s_3040bf_idx'), models.Index(fields=['codigo_fila', 'data_geracao'], name='tarefas_his_codigo__64e3d3_idx'), models.Index(fields=['tipo_acao', 'data_geracao'], name='tarefas_his_tipo_ac_4b7870_idx')],
            },
        ),
    ]
