# Generated by Django 5.2.7 on 2025-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_tarefa', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_cumprimento_exigencia_tarefa', models.TextField(blank=True, null=True)),
                ('siape_responsavel', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True)),
                ('nome_profissional_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_gex_responsavel', models.CharField(blank=True, max_length=10, null=True)),
                ('nome_gex_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('data_distribuicao_tarefa', models.DateField(blank=True, null=True)),
                ('data_ultima_atualizacao', models.DateField(blank=True, null=True)),
                ('data_fim_ultima_exigencia', models.DateField(blank=True, null=True)),
                ('data_processamento_tarefa', models.DateTimeField(blank=True, null=True)),
                ('tempo_ultima_exigencia_em_dias', models.IntegerField(blank=True, null=True)),
                ('tempo_em_pendencia_em_dias', models.IntegerField(default=0)),
                ('tempo_em_exigencia_em_dias', models.IntegerField(default=0)),
                ('tempo_ate_ultima_distribuicao_tarefa_em_dias', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Histórico de Tarefa',
                'verbose_name_plural': 'Históricos de Tarefas',
                'ordering': ['-registro_importacao__data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Importação')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo CSV')),
                ('registros_criados', models.PositiveIntegerField(default=0, verbose_name='Tarefas Novas Criadas')),
                ('registros_atualizados', models.PositiveIntegerField(default=0, verbose_name='Tarefas Atualizadas')),
                ('usuarios_criados', models.PositiveIntegerField(default=0, verbose_name='Usuários Criados')),
            ],
            options={
                'verbose_name': 'Registro de Importação',
                'verbose_name_plural': 'Registros de Importações',
                'ordering': ['-data_importacao'],
            },
        ),
    ]
