# Generated by Django 5.2.7 on 2025-10-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importar_csv', '0001_initial'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicotarefa',
            name='tarefa_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='tarefas.tarefa', verbose_name='Tarefa Original'),
        ),
    ]
