# Generated by Django 5.2.7 on 2025-10-22 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importar_csv', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimportacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='historicotarefa',
            name='registro_importacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_gerados', to='importar_csv.registroimportacao', verbose_name='Registro de Importação'),
        ),
    ]
