# Generated by Django 5.2.7 on 2025-10-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar_csv', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicotarefa',
            name='data_inicio_ultima_exigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início da Última Exigência'),
        ),
        migrations.AddField(
            model_name='historicotarefa',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Prazo'),
        ),
        migrations.AddField(
            model_name='historicotarefa',
            name='indicador_tarefa_reaberta',
            field=models.IntegerField(default=0, verbose_name='Indicador de Tarefa Reaberta'),
        ),
    ]
