# Generated by Django 5.2.7 on 2025-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar_csv', '0004_historicotarefa_data_inicio_ultima_exigencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimportacao',
            name='caminho_arquivo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do Arquivo Temporário'),
        ),
        migrations.AddField(
            model_name='registroimportacao',
            name='data_fim_processamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Processamento'),
        ),
        migrations.AddField(
            model_name='registroimportacao',
            name='data_inicio_processamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do Processamento'),
        ),
        migrations.AddField(
            model_name='registroimportacao',
            name='linhas_processadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Linhas Processadas'),
        ),
        migrations.AddField(
            model_name='registroimportacao',
            name='mensagem_erro',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro'),
        ),
        migrations.AddField(
            model_name='registroimportacao',
            name='progresso_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progresso (%)'),
        ),
        migrations.AddField(
            model_name='registroimportacao',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status da Importação'),
        ),
        migrations.AddField(
            model_name='registroimportacao',
            name='total_linhas',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Linhas no CSV'),
        ),
    ]
